### ISSUE TITLE
BOT driver: hang up while trying to start logical units that have already been stopped during a previous session.

### ISSUE THREAD

**Issue by FlyingBananaTree** [DarkMatterCore/libusbhsfs#9] opened 2020-12-08 22:43 UTC
**Describe the bug**
Hello, would you be able to help diagnose this bug?

After using a homebrew that makes use of libusbhsfs returning to that homebrew can result in a black screen or crash.

Please see https://github.com/rashevskyv/dbi/issues/7 for full reference including atmosphere crash report. I was able to reproduce this with the libusbhsfs example nro

**To Reproduce**
1. Run libusbhsfs example
2. Exit
3. Return to open libusbhsfs example
4. Black screen in application mode, crash in applet mode

**Please fill the following information:**
- Horizon OS (Switch FW) version: 10.2.0 + 11.0.0 tested
- CFW: Atmosphere 0.16.0 prerelease 2
- Atmosphère launch method (if applicable): fusee-primary or hekate fss0
- libusbhsfs version: 0.0.3
- Homebrew launch method: application or applet
- USB Mass Storage device specs: Kingston datatraveler 64GB exFAT pendrive

**Logfile**
I'm not getting the logfile, would you be able to provide a build that produces this?

**Comment by DarkMatterCore** [comment] 2020-12-08 22:56
Honestly, beats me. It's something my testers haven't been able to reproduce.

Please check if you're not running any additional sysmodules that also depend on USB host functionality.

**Comment by DarkMatterCore** [comment] 2020-12-08 22:59
I'll make a debug build and attach it here. The example app isn't linked against the debug build of the library by default.

**Comment by FlyingBananaTree** [comment] 2020-12-08 22:59
> 
> 
> Honestly, beats me. It's something my testers haven't been able to reproduce.
> 
> Please check if you're not running any additional sysmodules that also depend on USB host functionality.

I deactivated every single sysmodule for good measure, same result.

> 
> 
> I'll make a debug build and attach it here. The example app isn't linked against the debug build of the library by default.

Ok thank you.

**Comment by DarkMatterCore** [comment] 2020-12-08 23:07
[libusbhsfs-example.zip](https://github.com/DarkMatterCore/libusbhsfs/files/5662472/libusbhsfs-example.zip)

Please try this one.

**Comment by FlyingBananaTree** [comment] 2020-12-08 23:31
> 
> 
> [libusbhsfs-example.zip](https://github.com/DarkMatterCore/libusbhsfs/files/5662472/libusbhsfs-example.zip)
> 
> Please try this one.

Thanks. Here you go: https://gist.github.com/FlyingBananaTree/c42644cd1891d055b7f34ab933da634b

I found that the bug can be activated if for example you run the example app and then DBI or vice versa.

**Comment by DarkMatterCore** [comment] 2020-12-08 23:35
Hmm, it's really hard to tell what's going wrong here. The logfile is clean, up to the point where the background thread is being properly closed and all data is being properly freed.

Send me a screenshot of the crash in applet mode.

**Comment by FlyingBananaTree** [comment] 2020-12-08 23:44
> 
> 
> Hmm, it's really hard to tell what's going wrong here. The logfile is clean, up to the point where the background thread is being properly closed and all data is being properly freed.
> 
> Send me a screenshot of the crash in applet mode.

The atmosphere crash report is here https://gist.github.com/FlyingBananaTree/21675bfb212ecaf95e66b3b4a6dbf501

**Comment by DarkMatterCore** [comment] 2020-12-08 23:45
It's not useful to me. The crash report references DBI-relative addresses.

**Comment by FlyingBananaTree** [comment] 2020-12-08 23:51
> 
> 
> It's not useful to me. The crash report references DBI-relative addresses.

Unfortunately I can't trigger the crash with the example app, it just hangs when it reaches "Press + to exit" and can only be exited with the home button.

**Comment by DarkMatterCore** [comment] 2020-12-09 00:20
I'm really drawing a blank here. Could you please ask duckbill if they could check where is the crash taking place? They should be able to do so by using a DBI ELF for the specific DBI version/revision you used to generate that report + addr2line.

If the crash references a line number from libusbhsfs, I may be able to further look into this issue. But given the way things are right now, I just don't have enough info to know what's happening nor to fix the problem. It may even be a libnx issue, for all we know.

**Comment by DarkMatterCore** [comment] 2020-12-09 00:25
@FlyingBananaTree If possible, please use this build and run it up to the point where the hang up takes place. It will be much, much slower because all logfile writes will be flushed immediately, but all information should be preserved.

[libusbhsfs-example.zip](https://github.com/DarkMatterCore/libusbhsfs/files/5662726/libusbhsfs-example.zip)

**Comment by DarkMatterCore** [comment] 2020-12-09 00:27
Also, check if the application can recover from the hang up by disconnecting the USB drive before attempting to exit using the Home button.

**Comment by FlyingBananaTree** [comment] 2020-12-09 00:34
> 
> 
> @FlyingBananaTree If possible, please use this build and run it up to the point where the hang up takes place. It will be much, much slower because all logfile writes will be flushed immediately, but all information should be preserved.
> 
> [libusbhsfs-example.zip](https://github.com/DarkMatterCore/libusbhsfs/files/5662726/libusbhsfs-example.zip)

How much slower? It hasn't moved by "Press + the exit" for a few minutes.

> 
> 
> Also, check if the application can recover from the hang up by disconnecting the USB drive before attempting to exit using the Home button.

Yes, it does recover from the hang by removing the USB drive and exiting.

**Comment by DarkMatterCore** [comment] 2020-12-09 00:38
@FlyingBananaTree Alright, seems like we might be onto something here. Send me the new logfile - the one that holds the log session from when you removed the USB drive.

**Comment by FlyingBananaTree** [comment] 2020-12-09 00:44
> 
> 
> @FlyingBananaTree Alright, seems like we might be onto something here. Send me the new logfile - the one that holds the log session from when you removed the USB drive.

There you go: https://gist.github.com/FlyingBananaTree/986290087d13b311a44fa6007e765934

**Comment by DarkMatterCore** [comment] 2020-12-09 00:49
@FlyingBananaTree Interesting. Now please do the following:

1. Delete/move the current logfile from the SD card.
2. Start the example test app with no USB drives connected.
3. Connect the USB drive and wait for all tests to finish.
4. Attempt to exit the example test app via + button. If it hangs up (wait at least 10 seconds), disconnect the USB drive. The idea is to not use the Home button.
5. Send me the new logfile.

**Comment by FlyingBananaTree** [comment] 2020-12-09 00:53
https://gist.github.com/FlyingBananaTree/6c9ca32d24fe7799ed25035224631a42

I didn't have to use Home to exit, that only happens if I go back to the app a second time.

**Comment by DarkMatterCore** [comment] 2020-12-09 00:56
Ah, I see. So you're launching the example test app a second time without disconnecting the USB drive, right?

Does this generate a logfile similar to the one from the previous Gist?

**Comment by FlyingBananaTree** [comment] 2020-12-09 00:58
Yes the previous log is: use the app once -> exit normally -> return to homebrew menu and use the app again -> app is frozen -> disconnect drive -> exit normally

**Comment by DarkMatterCore** [comment] 2020-12-09 01:10
Alright, please try this build. Let's see if it is what I think it is.

[libusbhsfs-example.zip](https://github.com/DarkMatterCore/libusbhsfs/files/5662895/libusbhsfs-example.zip)

**Comment by FlyingBananaTree** [comment] 2020-12-09 01:11
> 
> 
> Alright, please try this build. Let's see if it is what I think it is.
> 
> [libusbhsfs-example.zip](https://github.com/DarkMatterCore/libusbhsfs/files/5662895/libusbhsfs-example.zip)

Any particular order you would like me to run this with? USB disconnected before running?

**Comment by DarkMatterCore** [comment] 2020-12-09 01:13
Just run the application a second time without removing the USB drive after successfully running + exiting the first time.

**Comment by FlyingBananaTree** [comment] 2020-12-09 01:14
> 
> 
> Just run the application a second time without removing the USB drive after successfully running + exiting the first time.

Currently it's frozen as soon as I start the first run.

**Comment by DarkMatterCore** [comment] 2020-12-09 01:17
Alright, please send me the logfile.

**Comment by FlyingBananaTree** [comment] 2020-12-09 01:24
> 
> 
> Alright, please send me the logfile.

I can't generate a logfile because it's frozen right away and removing the USB drive does not resolve that either as it did with the previous built. The logfiles are empty.

**Comment by DarkMatterCore** [comment] 2020-12-09 04:49
@FlyingBananaTree Sorry for the delay. Please test this new build.

[libusbhsfs-example.zip](https://github.com/DarkMatterCore/libusbhsfs/files/5663550/libusbhsfs-example.zip)

**Comment by FlyingBananaTree** [comment] 2020-12-09 07:50
> 
> 
> @FlyingBananaTree Sorry for the delay. Please test this new build.
> 
> [libusbhsfs-example.zip](https://github.com/DarkMatterCore/libusbhsfs/files/5663705/libusbhsfs-example.zip)

That build ran successfully on both the first and second runs, the bug did not occur on the second run and I was able to exit normally without removing the USB drive.

Here is the log from the second run: https://gist.github.com/FlyingBananaTree/9ed16de75b8e3dffe6ba42dbe6e385d1

**Comment by DarkMatterCore** [comment] 2020-12-09 09:08
@FlyingBananaTree Thanks for you help. I'll proceed to close the issue. The changes have already been pushed to the `dev` branch, and will be part of the next public release.

The real problem here is that the BOT driver from the library issues both Allow Medium Removal + Stop Unit commands while unmounting UMS devices that identify themselves as removable, which is exactly what the "Safely Remove" feature from Windows does.

Stopping logical units from UMS devices makes them completely unusable unless:

a. They're disconnected and reconnected.
b. A bus reset is performed.

The library was hanging because it kept waiting for a response from your USB drive, which was already stopped during the first session. The latest commit fixes this behaviour by checking if there are any UMS devices attached to the console right after the library is initialized, and if so, a bus reset is performed on every single one.

**Closed by DarkMatterCore** 2020-12-09 09:08 UTC
Labels: bug, fixed

**Comment by FlyingBananaTree** [comment] 2020-12-09 13:42
Thanks! To confirm the issue is fixed in the new DBI release compiled with the latest libusbhsfs commit.
