### ISSUE TITLE
BOT driver: filter invalid/unsupported peripheral qualifier and peripheral device type values from Inquiry data.

### ISSUE THREAD

**Issue by ginkuji** [DarkMatterCore/libusbhsfs#7] opened 2020-12-04 09:02 UTC
I am using the latest build of DBI 195. ( DBI is using the latest release of libusbhsfs)
The developer mentioned that I should post this concern on this github
Source: https://github.com/rashevskyv/dbi/issues/8

Running atmosphere 15 on 10.2 firmware
I am also running DBI on NSP forwarder.
I have three hardrives all formated to exfat

Two of my hardrives are using an enclosure (1 tera western digital, 2 tera toshiba). These are working well with DBI.
The third hardrive is a western digital passport external hardrive. DBI simply hangs after I tried accessing the files inside. I already tried reformating it but still, it won't read. The light indicator for the hardrive stays still.

Note:
I have tried all three hardrives with tinfoil and they all work. I do not know what causes the error for DBI.

**Comment by DarkMatterCore** [comment] 2020-12-04 09:05
@ginkuji Hi there, mate. Nice to meet you, and thanks for opening this issue.

This sounds like a BOT driver failure. I'll need you to provide a logfile so I can further analyze the issue and fix it. Please run the attached application, connect your USB HDD for ~20 seconds, disconnect it and exit by pression the + button.

[libusbhsfs-example.zip](https://github.com/DarkMatterCore/libusbhsfs/files/5641644/libusbhsfs-example.zip)

**Comment by ginkuji** [comment] 2020-12-04 09:54
Here are the log files. I tried twice to make sure. It hanged even though I present the + button so I pressed home. Thank you very much for considering my concern.
https://filebin.net/l2vb65fu0jtgq6h0

**Comment by DarkMatterCore** [comment] 2020-12-04 10:14
@ginkuji Thanks, that helps a lot.

This is indeed an issue with the BOT driver. Your USB HDD reports two logical units - the first one is properly initialized, and its FAT volume is properly mounted, but the second one fails to be initialized.

Even though a possible STALL status is cleared from both endpoints when this occurs, it seems it's not enough. That's why the application hangs as soon as the library attempts to send the next command to your USB HDD.

I'll look into it.

**Comment by DarkMatterCore** [comment] 2020-12-04 11:33
@ginkuji Please test the attached build. Let me know how it goes.

[libusbhsfs-example.zip](https://github.com/DarkMatterCore/libusbhsfs/files/5642431/libusbhsfs-example.zip)

**Comment by ginkuji** [comment] 2020-12-04 12:34
Here is the latest log. The hardrive is now blinking indicating that it is reading. The exit button however is not working. I pressed home again after 20 seconds.
https://filebin.net/3jjsrtmzz88zxwdu

**Comment by DarkMatterCore** [comment] 2020-12-04 13:15
@ginkuji It's all looking good now. It didn't get stuck this time around, though - FatFs just started reading free cluster info to determine the free space in the FAT volume.

This is usually a fast operation (<= 10 seconds), but since you're currently using a debug build of the library that logs every single read/written logical block, your time expectation is exceeded.

I'll create a normal build and send it to you so you can compare. The problem should be fixed now.

**Comment by ginkuji** [comment] 2020-12-04 13:21
Thank you! I will wait for the latest build. Glad I was able to contribute by reporting a bug.

**Comment by DarkMatterCore** [comment] 2020-12-04 13:24
@ginkuji And I'm glad you reported it. :)

Here's the normal build. It should be much faster.

[libusbhsfs-example.zip](https://github.com/DarkMatterCore/libusbhsfs/files/5642979/libusbhsfs-example.zip)

**Comment by ginkuji** [comment] 2020-12-04 13:49
Thank you. It now works.
I also noticed that the file copy sdmc -> ums0 failed (5)
Other than that + now works.

**Comment by DarkMatterCore** [comment] 2020-12-04 13:54
@ginkuji Excellent. Thanks a lot for helping test the changes. :)

**Comment by DarkMatterCore** [comment] 2020-12-04 13:55
That error at the end is expected behaviour - it tries to perform a r/w benchmark by copying a `test.file` file from the SD card to the USB drive.

**Comment by DarkMatterCore** [comment] 2020-12-04 15:10
Fixed in 404545e22e7998e039020561c093699c7d95ec5c.

This will be part of the next public release.

**Closed by DarkMatterCore** 2020-12-04 15:10 UTC
Labels: bug
